[project]
name = "ricks-vision-server"
version = "0.1.0"
description = "Backend for tracking the Rick's line"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.5",
]
