[project]
name = "ricks-vision-server"
version = "0.1.0"
description = "Backend for tracking the Rick's line"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.5",
    "opencv-python>=4.10.0.84",
    "pillow>=11.0.0",
    "streamlink>=7.0.0",
]
